### ISSUE TITLE
Differences between Normal and Text?

### ISSUE THREAD

**Issue by cssobral2013** [chiron-fonts/chiron-hei-hk#1]

**Comment by tamcy** [comment]
In this font, "Normal" is a font weight i.e. how bold it is, whereas "Text" is a subfamily of the font. It is a style that is sort of analogous to the the optical sizes in Source Serif 4. In the "Text" subfamily, non-LGC glyphs are scaled to ~96% of their original size so that they appear less tight (or not too tight in my perception) when used as an article's body text. I am not sure if the name "optical size" is suitable for this change because it's just a simple scale down, so I chose "padding" to denote the difference for the moment.

![padding](https://user-images.githubusercontent.com/959433/161362328-42813d08-4f90-48b3-94a9-48ad410f258d.gif)
